version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - rabbit34
      - rabbit35
      - rabbit36

  collectdamazon2017:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd.amazon2017.03
    depends_on:
      - fake_sfx
      - rabbit34
      - rabbit35
      - rabbit36

  rabbit34:
    image: rabbitmq:3.4-management

  rabbit35:
    image: rabbitmq:3.5-management

  rabbit36:
    image: rabbitmq:3.6-management

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
  
  test26: # this is to test that python2.6 works (because collectd is linked to 2.6 on amazon)
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectdamazon2017
