version: '2'
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: ~/code
          command: |
            sudo apt update && sudo apt install -yq python3-pip
            pip install -r test_requirements.txt
      - run:
          name: Run basic tests
          working_directory: ~/code
          command: bash verify.sh
      - run:
          name: Run integration tests
          working_directory: ~/code
          command: pytest -n4 integration_tests
